backend:
  name: git-gateway
  branch: master

media_folder: static/cms/images
public_folder: /images

collections:
  - name: news
    label: News
    folder: static/cms/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: home
    label: Home
    folder: static/cms/home
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - { label: Hero image, name: image, widget: image }
      - label: First section
        name: firstSection
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Partners
        name: partners
        widget: object
        fields:
          - { label: partner 1, name: partner1, widget: image }
          - { label: partner 2, name: partner2, widget: image }
      - label: Second section
        name: secondSection
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: image text, name: imageText, widget: string }
          - { label: image, name: image, widget: image }
      - label: News
        name: news
        widget: relation
        collection: news
        multiple: true
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
