backend:
  name: git-gateway
  branch: master

media_folder: src/cms/images
public_folder: /images

collections:
  - name: news
    label: News
    folder: src/cms/news/news
    create: true
    slug: 'news/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Text, name: text, widget: markdown }

  - name: home
    label: Home
    folder: src/cms/home
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - label: Hero image
        name: image
        widget: object
        fields:
          - { label: image, name: image, widget: image }
          - { label: alt, name: alt, widget: string }
      - label: First section
        name: firstSection
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Partners
        name: partners
        widget: object
        fields:
          - label: partner 1
            name: partner1
            widget: object
            fields:
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
          - label: partner 2
            name: partner2
            widget: object
            fields:
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
      - label: Second section
        name: secondSection
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - label: image
            name: image
            widget: object
            fields:
              - { label: image, name: image, widget: image }
              - { label: text, name: text, widget: string }
              - { label: alt, name: alt, widget: string }

  - name: history
    label: History
    folder: src/cms/history
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - label: Section One
        name: sectionOne
        widget: object
        fields:
          - label: column 1
            name: columnOne
            widget: object
            fields:
              - { label: heading, name: heading, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
          - label: column 2
            name: columnTwo
            widget: object
            fields:
              - { label: heading, name: heading, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
      - label: Section Two
        name: sectionTwo
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Section Three
        name: sectionThree
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }

  - name: contact
    label: Contact
    folder: src/cms/contact
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - label: Office 1
        name: officeOne
        widget: object
        fields:
          - { label: name, name: name, widget: string }
          - { label: street, name: street, widget: string }
          - { label: zip, name: zip, widget: string }
          - { label: city, name: city, widget: string }
          - { label: country, name: country, widget: string }
          - { label: latitude, name: lat, valueType: float, widget: number }
          - { label: longitude, name: long, valueType: float, widget: number }
      - label: Office 2
        name: officeTwo
        widget: object
        fields:
          - { label: name, name: name, widget: string }
          - { label: street, name: street, widget: string }
          - { label: zip, name: zip, widget: string }
          - { label: city, name: city, widget: string }
          - { label: country, name: country, widget: string }
          - { label: latitude, name: lat, valueType: float, widget: number }
          - { label: longitude, name: long, valueType: float, widget: number }
          - { label: country, name: country, widget: string }
      - label: Email
        name: emails
        widget: list
        fields:
          - { label: name, name: name, widget: string }
          - { label: email, name: email, widget: string }

  - name: 'awards'
    label: Awards
    folder: src/cms/awards
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Subheading, name: subheading, widget: string }
      - label: Section One
        name: sectionOne
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Section Two
        name: sectionTwo
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: text, name: text, widget: markdown }
      - label: Section Three
        name: sectionThree
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Section Four
        name: sectionFour
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: text, name: text, widget: markdown }
      - label: Section Five
        name: sectionFive
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: subheading, name: subheading, widget: string }
          - { label: column 2, name: column2, widget: markdown }
      - label: Section Six
        name: sectionSix
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: text, name: text, widget: markdown }
      - label: Section Seven
        name: sectionSeven
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: subheading, name: subheading, widget: string }
          - { label: column 2, name: column2, widget: markdown }

  - name: 'about'
    label: About
    folder: src/cms/about
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: Subheading, name: subheading, widget: string }
      - label: Section One
        name: sectionOne
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: text 1, name: text1, widget: markdown }
          - { label: text 2, name: text2, widget: markdown }
          - label: image
            name: image
            widget: object
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
          - label: offset image
            name: offsetImage
            widget: object
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: Section Two
        name: sectionTwo
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - { label: column 1, name: column1, widget: markdown }
          - { label: column 2, name: column2, widget: markdown }
      - label: Section Three
        name: sectionThree
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - label: Board Member One
            name: boardMemberOne
            widget: object
            fields:
              - { label: name, name: name, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
          - label: Board Member Two
            name: boardMemberTwo
            widget: object
            fields:
              - { label: name, name: name, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
      - label: Section Four
        name: sectionFour
        widget: object
        fields:
          - { label: heading, name: heading, widget: string }
          - label: Employee One
            name: employeeOne
            widget: object
            fields:
              - { label: name, name: name, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
          - label: Employee Two
            name: employeeTwo
            widget: object
            fields:
              - { label: name, name: name, widget: string }
              - { label: text, name: text, widget: markdown }
              - label: image
                name: image
                widget: object
                fields:
                  - { label: image, name: image, widget: image }
                  - { label: alt, name: alt, widget: string }
